---
version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: vince-riv

phases:
  pre_build:
    commands:
      - echo Checking for critical env vars
      - test -n "$IMAGE_REPO_NAME"
      - test -n "$CODEBUILD_SOURCE_VERSION"
      - test -n "$AWS_DEFAULT_REGION"
      - test -n "$AWS_ACCOUNT_ID"
      #- echo Logging in to Amazon ECR...
      #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - export IMAGE_TAG=$CODEBUILD_SOURCE_VERSION
      - git_describe=`git describe || true`
      - ecr_repo=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - container_image_tag=${IMAGE_REPO_NAME}:${IMAGE_NAME}-$IMAGE_TAG
      - echo
      - echo ENVIRONMENT
      - env | sort
      - echo
      - echo Building the Docker image...
      - docker build -t $container_image_tag .
      - docker tag $container_image_tag $ecr_repo:$IMAGE_TAG
      - test -z "$CODEBUILD_WEBHOOK_TRIGGER" || docker tag $container_image_tag $IMAGE_REPO_NAME:`echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -`
      - test -z "$git_describe" || docker tag $container_image_tag $IMAGE_REPO_NAME:$git_describe
  #post_build:
  #  commands:
  #    - echo Build completed on `date`
  #    - echo Pushing the Docker image...
  #    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
