---
name: Docker Build

on:
  push:
    tags: ['*']
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_REPO: vinceriv
  IMAGE_NAME: py3-flask

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:${{ github.sha }}
