---
name: Container image build and push

on:
  push:
    tags: ['*.*.*', '*.*.*-*']
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_REPO: vinceriv
  IMAGE_NAME: py3-flask

jobs:

  docker-build-and-push:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vinceriv/py3-flask
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
